"""
產生真實物理 fake data（用 materials/ 內建 nk 表 + tmm 套件正向計算）

提供三個經典樣品：
    1. 50 nm Au / sapphire        ← 金屬薄膜，含吸收
    2. 285 nm SiO2 / Si           ← 半導體業常見參考樣品（強干涉色）
    3. bare Si wafer              ← 基板裸片（沒有薄膜）

輸出：
    data/sample1_Au50_sapphire/{R_long.dat, R_wide.dat, T.dat, truth.txt}
    data/sample2_SiO2_285_Si/   {R_long.dat, R_wide.dat, T.dat, truth.txt}
    data/sample3_bare_Si/       {R_long.dat, R_wide.dat, T.dat, truth.txt}

truth.txt 記錄產生用的參數（厚度、材料、AOI），之後給 fitter 對答案
"""
import os
import sys
import numpy as np
import pandas as pd
import tmm

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MATERIALS = os.path.join(ROOT, 'materials')
DATA = os.path.join(ROOT, 'data')


# =============================================================================
# 材料 nk 載入器
# =============================================================================

def load_nk(name: str, wavelength_nm: np.ndarray) -> np.ndarray:
    """從 ellipsometry.core.dispersion.MaterialLibrary 取得 n + i·k

    使用與主程式一致的 PCHIP 插值，避免假資料/計算對不上
    """
    sys.path.insert(0, ROOT)
    from ellipsometry.core.dispersion import MaterialLibrary
    return MaterialLibrary.get(name).n_complex(wavelength_nm)


# =============================================================================
# TMM 計算（用 tmm 套件）
# =============================================================================

def calc_psi_delta_T(layers: list[dict], wavelength_nm: np.ndarray,
                     aoi_deg_list: list[float]):
    """正向計算 Ψ, Δ (反射) 和 T (穿透, AOI=0)

    Parameters
    ----------
    layers : list of dict
        每層 {'material': name, 'thickness_nm': float, 'coherent': bool}
        第一個必為 ambient, 最後必為 substrate
    wavelength_nm : ndarray
    aoi_deg_list : list of float

    Returns
    -------
    psi   : ndarray (Nw, Nangle), 度
    delta : ndarray (Nw, Nangle), 度
    T     : ndarray (Nw,), 0-1（normal incidence）
    """
    # 預先載入所有材料的 n_complex
    nk_table = {ly['material']: load_nk(ly['material'], wavelength_nm) for ly in layers}

    # 統一用「有限基板 + air exit」單一堆疊，與 ellipsometry.core.tmm_calc 一致
    # 這對應 WVASE 的「Substrate Backside Correction = ON」物理
    ambient_mat = layers[0]['material']
    if ambient_mat not in nk_table:
        nk_table[ambient_mat] = load_nk(ambient_mat, wavelength_nm)

    inner_layers = layers[1:]                                    # films + substrate
    mats         = [ambient_mat] + [ly['material'] for ly in inner_layers] + [ambient_mat]
    d_list       = [np.inf]      + [ly['thickness_nm'] for ly in inner_layers] + [np.inf]
    c_list       = ['i']         + [('c' if ly.get('coherent', True) else 'i') for ly in inner_layers] + ['i']

    Nw = len(wavelength_nm)
    Nang = len(aoi_deg_list)
    psi = np.zeros((Nw, Nang))
    delta = np.zeros((Nw, Nang))
    T = np.zeros(Nw)

    aoi_rad = [np.deg2rad(a) for a in aoi_deg_list]
    use_inc = any(c == 'i' for c in c_list[1:-1])

    for i, wl in enumerate(wavelength_nm):
        n_list = [nk_table[m][i] for m in mats]

        # 反射：每個 AOI
        for j, theta in enumerate(aoi_rad):
            if use_inc:
                rs = tmm.inc_tmm('s', n_list, d_list, c_list, theta, wl)
                rp = tmm.inc_tmm('p', n_list, d_list, c_list, theta, wl)
                Rs, Rp = rs['R'], rp['R']
                psi[i, j] = np.rad2deg(np.arctan(np.sqrt(max(Rp / max(Rs, 1e-30), 0))))
                # Δ：用相干版本取相位近似（背面非相干主要影響振幅）
                r = tmm.ellips(n_list, d_list, theta, wl)
                delta[i, j] = np.rad2deg(r['Delta'])
            else:
                r = tmm.ellips(n_list, d_list, theta, wl)
                psi[i, j] = np.rad2deg(r['psi'])
                delta[i, j] = np.rad2deg(r['Delta'])

        # 穿透：normal incidence
        inc = tmm.inc_tmm('s', n_list, d_list, c_list, 0.0, wl)
        T[i] = inc['T']

    return psi, delta, T


# =============================================================================
# 輸出格式
# =============================================================================

def write_wvase_long(path: str, wl: np.ndarray, angles: list[float],
                     psi: np.ndarray, delta: np.ndarray,
                     sigma_psi: float = 0.02, sigma_delta: float = 0.1):
    """WVASE 長格式：每 AOI 一段"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write('% Generated by make_fake_data.py via real TMM forward calculation\n')
        f.write('% nm\tPsi\tDelta\tErr(Psi)\tErr(Delta)\n')
        for j, a in enumerate(angles):
            f.write(f'% AOI = {a:.3f}\n')
            for i, w in enumerate(wl):
                f.write(f'{w:.3f}\t{psi[i,j]:.4f}\t{delta[i,j]:.4f}'
                        f'\t{sigma_psi:.3f}\t{sigma_delta:.3f}\n')


def write_wvase_wide(path: str, wl: np.ndarray, angles: list[float],
                     psi: np.ndarray, delta: np.ndarray):
    """WVASE 寬格式：欄位 nm, Psi_<aoi>, Del_<aoi>, ..."""
    header = ['nm']
    cols = [wl]
    for j, a in enumerate(angles):
        a_int = int(a)
        header += [f'Psi_{a_int}', f'Del_{a_int}']
        cols += [psi[:, j], delta[:, j]]
    arr = np.column_stack(cols)
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\t'.join(header) + '\n')
        np.savetxt(f, arr, fmt='%.4f', delimiter='\t')


def write_transmission(path: str, wl: np.ndarray, T: np.ndarray):
    with open(path, 'w', encoding='utf-8') as f:
        f.write('nm\tT\n')
        for w, t in zip(wl, T):
            f.write(f'{w:.3f}\t{t:.6f}\n')


def write_truth(path: str, layers: list[dict], wl: np.ndarray, angles: list[float]):
    """記錄 ground truth 給 fitter 對答案"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write('# Ground truth — fake data 產生時使用的真實參數\n\n')
        f.write(f'wavelength_range_nm: [{wl.min():.0f}, {wl.max():.0f}]\n')
        f.write(f'wavelength_step_nm: {wl[1]-wl[0]:.3f}\n')
        f.write(f'angles_deg: {angles}\n\n')
        f.write('layers (top to bottom):\n')
        for ly in layers:
            f.write(f'  - material: {ly["material"]:10s}  '
                    f'thickness_nm: {ly["thickness_nm"]:<10}  '
                    f'coherent: {ly.get("coherent", True)}\n')


# =============================================================================
# 三個樣品定義
# =============================================================================

SAMPLES = {
    'sample1_Au50_sapphire': {
        'description': '50 nm Au on sapphire (Al2O3) 透明基板',
        'layers': [
            {'material': 'air',   'thickness_nm': np.inf},
            {'material': 'Au',    'thickness_nm': 50,        'coherent': True},
            {'material': 'Al2O3', 'thickness_nm': 1_000_000, 'coherent': False},  # 1 mm
        ],
    },
    'sample2_SiO2_285_Si': {
        'description': '285 nm SiO2 / Si — 半導體業經典參考樣品',
        'layers': [
            {'material': 'air',  'thickness_nm': np.inf},
            {'material': 'SiO2', 'thickness_nm': 285,         'coherent': True},
            {'material': 'Si',   'thickness_nm': 1_000_000,   'coherent': False},
        ],
    },
    'sample3_bare_Si': {
        'description': 'Bare Si wafer (純基板裸片，無薄膜)',
        'layers': [
            {'material': 'air', 'thickness_nm': np.inf},
            {'material': 'Si',  'thickness_nm': 1_000_000, 'coherent': False},
        ],
    },
}


# =============================================================================
# 主流程
# =============================================================================

def main():
    wl = np.arange(300, 2001, 10, dtype=float)        # 171 點
    angles = [65.0, 70.0, 75.0]

    print(f'產生 fake data：波長 {wl[0]:.0f}-{wl[-1]:.0f} nm step {wl[1]-wl[0]:.0f}, '
          f'AOI={angles}, {len(SAMPLES)} 個樣品')

    for sample_name, sample in SAMPLES.items():
        out_dir = os.path.join(DATA, sample_name)
        os.makedirs(out_dir, exist_ok=True)
        print(f'\n[{sample_name}] {sample["description"]}')

        psi, delta, T = calc_psi_delta_T(sample['layers'], wl, angles)

        # 健全檢查
        if np.any(np.isnan(psi)) or np.any(np.isnan(delta)):
            print('  ✗ 有 NaN！檢查材料 nk 範圍')
            continue

        # 寫三種格式
        f_long = os.path.join(out_dir, 'R_long.dat')
        f_wide = os.path.join(out_dir, 'R_wide.dat')
        f_T    = os.path.join(out_dir, 'T.dat')
        f_truth= os.path.join(out_dir, 'truth.txt')

        write_wvase_long(f_long, wl, angles, psi, delta)
        write_wvase_wide(f_wide, wl, angles, psi, delta)
        write_transmission(f_T, wl, T)
        write_truth(f_truth, sample['layers'], wl, angles)

        # 列關鍵點驗證
        print(f'  Ψ 範圍: [{psi.min():.2f}, {psi.max():.2f}] deg')
        print(f'  Δ 範圍: [{delta.min():.2f}, {delta.max():.2f}] deg')
        print(f'  T 範圍: [{T.min():.4f}, {T.max():.4f}]')
        print(f'  ✓ 輸出至 data/{sample_name}/')


if __name__ == '__main__':
    main()
